import React, { Component, Suspense, lazy, useEffect, useMemo, useRef, useState } from 'react';
import {createRoot} from 'react-dom/client';
import {Network, Coins, Landmark, Activity, SlidersHorizontal, BookOpen, List, Bell, Search, RefreshCw, Crosshair, Check, ArrowUp, ArrowDown, Layers, Menu, FlaskConical} from 'lucide-react';
import ForceGraph2D from 'react-force-graph-2d';
import * as THREE from 'three';
import './style.css';
import PaperPanel from './PaperPanel';
const ForceGraph3D = lazy(()=>import('react-force-graph-3d'));
type Position={symbol:string;market:string;quantity:string;price:string|null;value:string|null;unrealized:string|null;side?:string;entry_price?:string;leverage?:string;margin_type?:string};
type Snapshot={as_of:string;currency:string;cash:string;equity:string|null;priced_subtotal:string;unrealized:string|null;positions:Position[];unpriced:string[]};
type AccountView={snapshot:Snapshot|null;collector:{status:string};history:{as_of:string;equity:string|null}[]};
type Overview={snapshot:Snapshot|null;accounts:{upbit:AccountView;binance_futures:AccountView};stale:boolean;collector:{status:string};runtime:Record<string,unknown>;settings:Record<string,unknown>;recommendations:any[];recommendations_as_of:string;regime:string;history:{as_of:string;equity:string|null}[];connections:{id:string;label:string;status:string}[]};
type Node={id:string;label:string;type:string;color:string;detail:string;val:number};
const money=(n:unknown,currency='KRW')=>n===null||n===undefined?'미확인':currency==='USD'?'$'+Number(n).toLocaleString('ko-KR',{maximumFractionDigits:2}):Number(n).toLocaleString('ko-KR',{maximumFractionDigits:0})+'원';
const stamp=(s:unknown)=>typeof s==='string'&&s? s.includes('T')?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):s+' KST':'기록 없음';
const statusLabel=(s:string)=>({connected:'조회 정상',offline_ready:'오프라인 연구 준비됨',disabled:'인증 전 · 비활성',not_configured:'연결 미설정',missing_credentials:'인증키 미설정',not_connected:'수집기 대기',http_401:'인증 실패 · 401',http_403:'권한 또는 IP 확인 · 403',collection_failed:'조회 실패'}[s]||s);
const workerLabel=(r:Record<string,unknown>|undefined)=>{if(r?.paused)return '중지 설정';const heartbeat=typeof r?.last_heartbeat==='string'?new Date(r.last_heartbeat).getTime():0;if(!heartbeat||Date.now()-heartbeat>90000)return '실행 확인 안 됨';return r?.real_trade_enabled?'실거래 프로세스 응답':'모의 프로세스 응답';};
async function get(path:string){const r=await fetch('/api/v1/'+path);if(!r.ok)throw Error('조회 실패 '+r.status);return r.json();}
class GraphBoundary extends Component<{children:React.ReactNode;resetKey:string},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return {error:true};}componentDidUpdate(p:{resetKey:string}){if(p.resetKey!==this.props.resetKey&&this.state.error)this.setState({error:false});}render(){return this.state.error?<div className="empty">그래픽을 표시할 수 없습니다. 2D 또는 목록을 선택하세요.</div>:this.props.children;}}
function Graph({data,select,mode}:{data:{nodes:Node[];links:{source:string;target:string}[]};select:(n:Node)=>void;mode:string}){
 const holder=useRef<HTMLDivElement>(null);const graph=useRef<any>(null);const [width,setWidth]=useState(600);
 useEffect(()=>{const ob=new ResizeObserver(es=>setWidth(es[0].contentRect.width));if(holder.current)ob.observe(holder.current);return ()=>ob.disconnect();},[]);
 const labelSprite=(n:any)=>{const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const ctx=canvas.getContext('2d')!;ctx.font=n.type==='account'?'600 30px Arial':'500 26px Arial';ctx.fillStyle='#dae7ee';ctx.textAlign='center';ctx.textBaseline='middle';ctx.shadowColor='#0b0e12';ctx.shadowBlur=8;ctx.fillText(n.label,256,48);const texture=new THREE.CanvasTexture(canvas);texture.needsUpdate=true;const material=new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false});const sprite=new THREE.Sprite(material);sprite.scale.set(n.type==='account'?34:27, n.type==='account'?6.5:5, 1);return sprite;};
 const common={graphData:structuredClone(data),width,height:430,backgroundColor:'#0b0e12',nodeLabel:(n:any)=>`${n.label}\n${n.detail}`,nodeColor:'color',linkColor:()=> '#315257',nodeVal:'val',onNodeClick:(n:any)=>select(n),cooldownTicks:70,onEngineStop:()=>graph.current?.zoomToFit(300,55)};
 return <div className="graph-holder" ref={holder}><button className="fit icon" title="전체 노드 맞춤" aria-label="전체 노드 맞춤" onClick={()=>graph.current?.zoomToFit(400,50)}><Crosshair size={17}/></button><GraphBoundary resetKey={mode}><Suspense fallback={<div className="empty">그래프 불러오는 중</div>}>{mode==='3d'?<ForceGraph3D {...common} ref={graph} nodeThreeObject={labelSprite} nodeThreeObjectExtend={false}/>:<ForceGraph2D {...common} ref={graph} nodeCanvasObject={(n:any,ctx,scale)=>{const r=n.type==='account'?10:6;ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(n.x,n.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=n.color;ctx.globalAlpha=.25;ctx.beginPath();ctx.arc(n.x,n.y,r+5,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;if(scale>.55){ctx.font=`${12/scale}px sans-serif`;ctx.textAlign='center';ctx.fillStyle='#dae7ee';ctx.fillText(n.label,n.x,n.y+r+17/scale);}}}/>}</Suspense></GraphBoundary></div>;
}
const nav=[['all','통합 운영',Network],['upbit','Upbit 현물',Coins],['stock','국내주식',Landmark],['futures','Binance 선물',Activity],['events','판단·거래 이력',List],['lab','전략 연구실',FlaskConical],['universe','종목·그룹',Layers],['settings','전략 설정',SlidersHorizontal],['notifications','알림 설계',Bell],['help','사용법·용어',BookOpen]] as const;
function App(){
 const [page,setPage]=useState('all'),[tab,setTab]=useState('graph'),[mode,setMode]=useState('2d'),[data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<Node|null>(null),[events,setEvents]=useState<any[]>([]),[strategies,setStrategies]=useState<any>(null),[query,setQuery]=useState(''),[universe,setUniverse]=useState<Record<string,any>>({}),[chosen,setChosen]=useState<string[]>([]),[group,setGroup]=useState('watch'),[drafts,setDrafts]=useState<any[]>([]),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[saving,setSaving]=useState(false);
 const [draft,setDraft]=useState({mode:'approval',buy_amount:20000,interval:'3m',leverage:2,report_minutes:5,events:['risk','fill','recommendation','summary']});
 const refresh=()=>get('overview').then(d=>{setData(d);setError('');}).catch(e=>setError(e.message));
 useEffect(()=>{refresh();get('events').then(setEvents).catch(()=>setError('이력 조회 실패'));get('strategies').then(setStrategies).catch(()=>setError('전략 연구실 조회 실패'));get('universe').then(setUniverse).catch(()=>{});get('drafts').then(setDrafts).catch(()=>{});const timer=setInterval(refresh,5000);return()=>clearInterval(timer);},[]);
 const graphData=useMemo(()=>{const nodes:Node[]=[{id:'root',label:'통합 운영',type:'account',color:'#45e3df',val:8,detail:'조회 API 기반 운영 관계입니다. 실제 신경망 모델을 의미하지 않습니다.'}];const links:{source:string;target:string}[]=[];for(const c of data?.connections||[]){nodes.push({id:c.id,label:c.label,type:'account',color:c.id==='futures'?'#e39dcc':c.id==='stock'?'#eed26b':'#45e3df',val:5,detail:statusLabel(c.status)});links.push({source:'root',target:c.id});}for(const p of data?.accounts?.upbit.snapshot?.positions||[]){nodes.push({id:p.market,label:p.symbol,type:'position',color:'#94e4bb',val:2,detail:`보유 ${p.quantity} · 평가 ${money(p.value)} · 손익 ${money(p.unrealized)}`});links.push({source:'upbit',target:p.market});}for(const p of data?.accounts?.binance_futures.snapshot?.positions||[]){nodes.push({id:p.market,label:p.symbol,type:'position',color:'#e39dcc',val:2,detail:`${p.side||'BOTH'} ${p.quantity} · 평가 ${money(p.value,'USD')} · 손익 ${money(p.unrealized,'USD')}`});links.push({source:'futures',target:p.market});}for(const r of (data?.recommendations||[]).slice(0,15)){const id='rec:'+r.market;nodes.push({id,label:r.market,type:'signal',color:'#e6c86c',val:2,detail:(r.reasons||[]).join(' · ')||r.strategy_label});links.push({source:'upbit',target:id});}return {nodes,links};},[data?.snapshot?.as_of,data?.accounts?.binance_futures.snapshot?.as_of,data?.recommendations_as_of,data?.collector.status]);
 const title=nav.find(n=>n[0]===page)?.[1]||'통합 운영';const account=page==='futures'?data?.accounts?.binance_futures:data?.accounts?.upbit;const disconnected=page==='stock'||(page==='futures'&&!account?.snapshot);const snapshot=disconnected?null:account?.snapshot;const currency=snapshot?.currency||'KRW';const accountHistory=account?.history||[];const accountStatus=page==='lab'?'offline_ready':account?.collector.status||'not_connected';const pageStale=page==='lab'?false:!snapshot||(Date.now()-new Date(snapshot.as_of).getTime())>90000;const visiblePositions=(snapshot?.positions||[]).filter(p=>p.symbol.toLowerCase().includes(query.toLowerCase()));
 const save=async(scope:string)=>{setSaving(true);setNotice('');try{const res=await fetch('/api/v1/drafts',{method:'POST',headers:{'Content-Type':'application/json','X-Neural-Client':'dashboard'},body:JSON.stringify({...draft,scope,symbols:chosen,group})});if(!res.ok)throw Error('입력값 또는 저장 요청을 확인하세요.');const d=await res.json();setNotice(`초안 #${d.id} 저장됨. 기존 워커에 적용되지 않았습니다.`);setDrafts(await get('drafts'));}catch(e){setNotice(String(e));}finally{setSaving(false);}};
 return <div className="app"><aside className={menu?'open':''}><div className="brand"><Network size={24}/><span>NEURAL<span className="trade"> / TRADE</span></span></div><div className="workspace">MULTI-ASSET WORKSPACE</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setNotice('');setQuery('');setMenu(false);}}><Icon size={18}/>{label}</button>)}</nav><div className="side-bottom"><span className="dot"/>조회 서비스<br/><small>BUILD 02 / READ ONLY</small></div></aside><div className="content"><header><button className="icon mobile" onClick={()=>setMenu(!menu)} aria-label="메뉴"><Menu size={20}/></button><span className="crumb">WORKSPACE <span>/ {title}</span></span><span className="readonly">주문 실행 미연결</span><button className="icon" title="새로고침" aria-label="새로고침" onClick={refresh}><RefreshCw size={17}/></button></header><main><div className="heading"><div><p className="eyebrow">NEURAL OPERATIONS</p><h1>{title}</h1></div><div className="source"><span className={pageStale?'warning':'good'}>{statusLabel(accountStatus)}</span><small>{stamp(snapshot?.as_of)}</small></div></div><div className="parameters"><span>기존 운영 단계 <b>{String(data?.settings.operation_mode??'—')}</b></span><span>성향 <b>{String(data?.settings.trading_style??'—')}</b></span><span>기본 주문 <b>{money(data?.settings.buy_amount_krw)}</b></span><span>최대 보유 <b>{String(data?.settings.max_positions??'—')}</b></span><span>기존 워커 <b>{workerLabel(data?.runtime)}</b></span></div>{error&&<div className="alert" role="alert">{error}</div>}
 {['all','upbit','stock','futures'].includes(page)?<>{disconnected?<div className="connection-empty"><Landmark size={30}/><h2>{title} 연결 대기</h2><p>{page==='stock'?'증권사·계좌 유형 확정 후 조회 어댑터를 연결합니다.':accountStatus==='disabled'?'조회 어댑터 구축 완료 · 인증과 IP 등록 전까지 안전하게 비활성화되어 있습니다.':'선물 계좌 인증키와 허용 IP를 확인하세요.'}</p><p>연결되지 않은 자산은 통합 합계에 포함되지 않습니다.</p></div>:<><div className="metrics"><div><span>조회된 순자산 · {currency}</span><strong>{money(snapshot?.equity,currency)}</strong><small>{page==='futures'?'Binance 선물 계좌 단독 표시':'Upbit 계좌 단독 표시'}</small></div><div><span>{page==='futures'?'주문 가능 잔고':'현금 · 주문 잠금 포함'}</span><strong>{money(snapshot?.cash,currency)}</strong><small>{currency} 기준</small></div><div><span>미실현손익</span><strong className={Number(snapshot?.unrealized)>=0?'good':'bad'}>{money(snapshot?.unrealized,currency)}</strong><small>{page==='futures'?'Binance 제공값 · 수수료 전':'평균매수가 기준 · 수수료 전'}</small></div></div>{pageStale&&<div className="alert">현재 수집 데이터가 없거나 90초 이상 지연되었습니다. 표시값의 기준시각을 확인하세요.</div>}{!!snapshot?.unpriced.length&&<div className="alert">가격 미확인: {snapshot.unpriced.join(', ')} · 합계 검증이 필요합니다.</div>}</>}
 <div className="view-head"><div className="tabs">{[['graph','운영 연결망'],['assets','자산 추이'],['positions','보유자산']].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='graph'&&<div className="segmented">{['2d','3d','list'].map(x=><button key={x} className={mode===x?'active':''} onClick={()=>setMode(x)}>{x==='list'?'목록':x.toUpperCase()}</button>)}</div>}</div>
 {tab==='graph'?<><div className="graph-meta"><span>● 계좌 <span className="good">● 보유</span> <span className="warning">● 추천</span></span><small>전체 시장 연결 상태 · {graphData.nodes.length}개 노드</small></div>{mode==='list'?<div className="node-list">{graphData.nodes.map(n=><button key={n.id} onClick={()=>setSelected(n)}>{n.label}<small>{n.type}</small></button>)}</div>:<Graph data={graphData} mode={mode} select={setSelected}/>}<div className="selection"><Network size={20}/><div><b>{selected?.label||'전체 운영 연결망'}</b><p>{selected?.detail||'계좌·보유자산·추천 기록을 연결합니다. 노드를 선택하면 근거가 표시됩니다.'}</p></div></div></>:tab==='assets'?<div className="chart-area"><h3>{page==='futures'?'Binance 선물':'Upbit'} 순자산 추이</h3>{accountHistory.filter(h=>h.equity!==null).length<2?<div className="empty">서로 다른 시각의 수집 기록이 두 개 이상 필요합니다.</div>:<EquityChart values={accountHistory} currency={currency}/>}</div>:null}
 <div className="section-title"><h2>{page==='futures'?'선물 포지션':'보유자산'} <small>{visiblePositions.length}</small></h2><label className="search"><Search size={16}/><input placeholder="종목 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-scroll"><table><thead><tr><th>종목</th><th>보유수량</th><th>현재가</th><th>평가액</th><th>미실현손익</th></tr></thead><tbody>{visiblePositions.map(p=><tr key={p.market} onClick={()=>setSelected(graphData.nodes.find(n=>n.id===p.market)||null)}><td><b>{p.symbol}</b><small>{p.side?`${p.side} · ${p.leverage||'—'}x · ${p.margin_type}`:p.market}</small></td><td>{Number(p.quantity).toLocaleString('ko-KR',{maximumFractionDigits:8})}</td><td>{money(p.price,currency)}</td><td>{money(p.value,currency)}</td><td className={Number(p.unrealized)>=0?'good':'bad'}>{money(p.unrealized,currency)}</td></tr>)}</tbody></table>{!visiblePositions.length&&<div className="empty">표시할 보유자산이 없습니다. 연결 상태와 검색 조건을 확인하세요.</div>}</div></>:null}
 {page==='events'&&<><div className="section-title"><h2>기존 원장 기록</h2><label className="search"><Search size={16}/><input placeholder="종목 · 이벤트 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p className="muted">가져온 이벤트입니다. 주문 요청과 실제 체결을 동일하게 집계하지 않습니다.</p><div className="table-scroll"><table><thead><tr><th>기록시각</th><th>이벤트</th><th>종목</th><th>사유</th></tr></thead><tbody>{events.filter(e=>JSON.stringify(e).toLowerCase().includes(query.toLowerCase())).map(e=><tr key={e.id}><td>{e.time}</td><td>{e.kind}</td><td>{e.payload.market||'—'}</td><td className="wrap">{e.payload.reason||e.payload.strategy_label||'—'}</td></tr>)}</tbody></table>{!events.length&&<div className="empty">가져온 기록이 없습니다.</div>}</div></>}
 {page==='lab'&&<><h2>오프라인 전략 후보</h2><p className="muted">아래 성과는 고정된 합성 캔들로 기능만 검증한 결과이며 실제 수익 예상치가 아닙니다. 수수료와 슬리피지는 각각 0.05%로 반영됩니다.</p><div className="table-scroll"><table><thead><tr><th>전략</th><th>진입 조건</th><th>주요 위험</th><th>거래 수</th><th>승률</th><th>순수익</th><th>최대낙폭</th><th>손익비</th></tr></thead><tbody>{(strategies?.catalog||[]).map((s:any)=>{const r=(strategies?.demo?.reports||[]).find((x:any)=>x.strategy===s.id)||{};return <tr key={s.id}><td><b>{s.name}</b><small>{s.market} · 연결 미사용</small></td><td className="wrap">{s.entry}</td><td className="wrap bad">{s.risk}</td><td>{r.trades??'—'}</td><td>{r.win_rate_pct??'—'}%</td><td className={Number(r.net_return_pct)>=0?'good':'bad'}>{r.net_return_pct??'—'}%</td><td className="bad">{r.max_drawdown_pct??'—'}%</td><td>{r.profit_factor??'—'}</td></tr>})}</tbody></table></div><div className="alert">실데이터 연결 전에는 전략을 활성화할 수 없습니다. 이후 과거 데이터 기간 분리 검증과 모의운영을 통과해야 합니다.</div></>}
 {page==='universe'&&<><div className="section-title"><h2>종목 선택 초안</h2><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="종목 검색"/></label></div><div className="field"><label>새 그룹 이름<input value={group} maxLength={40} onChange={e=>setGroup(e.target.value)}/></label><span>{chosen.length}개 선택</span></div><div className="universe">{Object.entries(universe).filter(([s])=>s.includes(query.toUpperCase())).map(([s,v])=><label key={s}><input type="checkbox" checked={chosen.includes(s)} onChange={e=>setChosen(e.target.checked?[...chosen,s]:chosen.filter(x=>x!==s))}/><span>{s}<small>현재 그룹: {String(v.group||'미분류')}</small></span></label>)}</div><button className="primary" disabled={saving} onClick={()=>save('universe')}><Check size={17}/>그룹 초안 저장</button></>}
 {page==='settings'&&<><h2>신규 전략 설정 초안</h2><p className="muted">저장한 초안은 신규 원장에 보관됩니다. 활성화 기능과 주문 실행기는 아직 연결되지 않았습니다.</p><div className="form-grid"><label>운영 단계<select value={draft.mode} onChange={e=>setDraft({...draft,mode:e.target.value})}><option value="analysis">분석 전용</option><option value="approval">승인형</option><option value="automatic">설정 범위 자동</option></select></label><label>기본 주문금액 · 원<input type="number" min="5000" max="10000000" value={draft.buy_amount} onChange={e=>setDraft({...draft,buy_amount:Number(e.target.value)})}/></label><label>실험 봉 주기<select value={draft.interval} onChange={e=>setDraft({...draft,interval:e.target.value})}><option value="1m">1분 · 파생 실험</option><option value="3m">3분 · 원본 비교</option><option value="5m">5분</option></select></label><label>선물 레버리지 상한<input type="number" min="1" max="2" value={draft.leverage} onChange={e=>setDraft({...draft,leverage:Number(e.target.value)})}/></label></div><button className="primary" disabled={saving} onClick={()=>save('trading')}><Check size={17}/>설정 초안 저장</button></>}
 {page==='notifications'&&<><h2>알림 유형과 순서 초안</h2><p className="muted">기존 Telegram 발송 설정에는 아직 적용되지 않습니다.</p><label className="field">정기 요약 · 분<input type="number" min="1" max="1440" value={draft.report_minutes} onChange={e=>setDraft({...draft,report_minutes:Number(e.target.value)})}/></label>{draft.events.map((e,i)=><div className="notification-row" key={e}><span>{i+1}</span><b>{{risk:'위험·보호 실패',fill:'체결 결과',recommendation:'추천·승인',summary:'정기 요약'}[e]}</b><button className="icon" disabled={i===0} title="우선순위 올리기" aria-label={'우선순위 올리기 '+e} onClick={()=>{const a=[...draft.events];[a[i-1],a[i]]=[a[i],a[i-1]];setDraft({...draft,events:a});}}><ArrowUp size={17}/></button><button className="icon" disabled={i===draft.events.length-1} title="우선순위 내리기" aria-label={'우선순위 내리기 '+e} onClick={()=>{const a=[...draft.events];[a[i+1],a[i]]=[a[i],a[i+1]];setDraft({...draft,events:a});}}><ArrowDown size={17}/></button></div>)}<button className="primary" disabled={saving} onClick={()=>save('notifications')}><Check size={17}/>알림 초안 저장</button></>}
 {['settings','notifications','universe'].includes(page)&&<><p className="save-notice" role="status">{notice}</p><h3>저장 이력</h3>{drafts.slice(0,6).map(d=><div className="draft-row" key={d.id}><b>#{d.id} · {d.scope}</b><span>{stamp(d.time)}</span><small>미적용 초안</small></div>)}</>}
 {page==='help'&&<><h2>운영과 데이터 읽기</h2>{[['현재 구축 범위','기존 Upbit 계좌의 읽기 전용 수집, 원장 가져오기, 운영 연결망과 설정 초안 저장을 제공합니다. 기존 거래 워커는 독립적입니다.'],['순자산','KRW 현금과 모든 평가 가능한 보유자산을 합산합니다. 가격을 확인할 수 없는 자산이 있으면 전체 합계를 미확인으로 표시합니다.'],['뉴런형 연결망','실제 계좌와 기록의 관계입니다. 신경망 모델의 내부 가중치나 승률을 표현하지 않습니다.'],['단주기 매매','화면 갱신은 5초, 잔고 수집은 30초입니다. 주문 주기와 별개이며 1분봉 전략은 아직 실행되지 않습니다.'],['미실현손익','보유수량 × (현재가 − 평균매수가)입니다. 수수료 전이며, 매입 원가가 확인되지 않으면 미확인입니다.'],['설정 초안','원장에 저장되지만 활성화되지 않은 제안입니다. 상단 파라미터는 기존 워커의 설정값을 표시합니다.'],['서버 이전','기존 워커 중지와 최종 데이터 복원, 거래소 대사 후 새 서버를 활성화해야 합니다. 두 서버의 동시 주문을 금지합니다.']].map(([h,p])=><details key={h} open><summary>{h}</summary><p>{p}</p></details>)}</>}
 <footer><span>NEURAL TRADE · BUILD 02</span><span>LIVE 조회 / 신규 주문 기능 없음</span></footer></main></div></div>;
}
function EquityChart({values,currency='KRW'}:{values:{as_of:string;equity:string|null}[];currency?:string}){const v=values.filter(x=>x.equity!==null);const ns=v.map(x=>Number(x.equity));const lo=Math.min(...ns),hi=Math.max(...ns);const range=Math.max(hi-lo,1);const pts=ns.map((n,i)=>`${20+i/(ns.length-1)*740},${190-(n-lo)/range*160}`).join(' ');return <><div className="chart-caption"><span>{money(hi,currency)}</span><span>{money(lo,currency)}</span></div><svg viewBox="0 0 780 220" className="equity-chart" role="img" aria-label="수집 시점별 순자산 추이"><path d="M20 30H760 M20 110H760 M20 190H760" stroke="#2a353c"/><polyline fill="none" stroke="#45e3df" strokeWidth="2" points={pts}/></svg><div className="chart-caption"><span>{stamp(v[0].as_of)}</span><span>{stamp(v[v.length-1].as_of)}</span></div></>}
createRoot(document.getElementById('root')!).render(<><PaperPanel/><App/></>);
